//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnDataExport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_calendar
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string from_time { get; set; }
        public string to_time { get; set; }
        public string event_type { get; set; }
        public string event_code { get; set; }
        public string customer { get; set; }
        public int status { get; set; }
        public string med_cert { get; set; }
        public int fine { get; set; }
        public System.DateTime chgdat { get; set; }
        public int users_id { get; set; }
        public int recby { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
