//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnDataExport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class istab
    {
        public istab()
        {
            this.problem = new HashSet<problem>();
            this.serial = new HashSet<serial>();
            this.serial1 = new HashSet<serial>();
            this.serial2 = new HashSet<serial>();
            this.serial3 = new HashSet<serial>();
        }
    
        public int id { get; set; }
        public string tabtyp { get; set; }
        public string typcod { get; set; }
        public string abbreviate_en { get; set; }
        public string abbreviate_th { get; set; }
        public string typdes_en { get; set; }
        public string typdes_th { get; set; }
        public System.DateTime chgdat { get; set; }
        public int recby { get; set; }
    
        public virtual users users { get; set; }
        public virtual ICollection<problem> problem { get; set; }
        public virtual ICollection<serial> serial { get; set; }
        public virtual ICollection<serial> serial1 { get; set; }
        public virtual ICollection<serial> serial2 { get; set; }
        public virtual ICollection<serial> serial3 { get; set; }
    }
}
