//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnDataExport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mac_allowed
    {
        public int id { get; set; }
        public string mac_address { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_at { get; set; }
    }
}
