//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnDataExport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serial
    {
        public serial()
        {
            this.cloud_srv = new HashSet<cloud_srv>();
            this.ma = new HashSet<ma>();
            this.problem = new HashSet<problem>();
            this.serial_password = new HashSet<serial_password>();
        }
    
        public int id { get; set; }
        public string sernum { get; set; }
        public string oldnum { get; set; }
        public string version { get; set; }
        public string contact { get; set; }
        public string position { get; set; }
        public string prenam { get; set; }
        public string compnam { get; set; }
        public string addr01 { get; set; }
        public string addr02 { get; set; }
        public string addr03 { get; set; }
        public string zipcod { get; set; }
        public string telnum { get; set; }
        public string faxnum { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> busityp { get; set; }
        public string busides { get; set; }
        public Nullable<System.DateTime> purdat { get; set; }
        public Nullable<System.DateTime> expdat { get; set; }
        public string branch { get; set; }
        public Nullable<System.DateTime> manual { get; set; }
        public string upfree { get; set; }
        public string refnum { get; set; }
        public string remark { get; set; }
        public Nullable<int> howknown { get; set; }
        public Nullable<int> verext { get; set; }
        public Nullable<System.DateTime> verextdat { get; set; }
        public System.DateTime chgdat { get; set; }
        public Nullable<int> dealer_id { get; set; }
        public int recby { get; set; }
    
        public virtual ICollection<cloud_srv> cloud_srv { get; set; }
        public virtual dealer dealer { get; set; }
        public virtual istab istab { get; set; }
        public virtual istab istab1 { get; set; }
        public virtual istab istab2 { get; set; }
        public virtual istab istab3 { get; set; }
        public virtual ICollection<ma> ma { get; set; }
        public virtual ICollection<problem> problem { get; set; }
        public virtual ICollection<serial_password> serial_password { get; set; }
        public virtual users users { get; set; }
    }
}
